"""added email notification table

Revision ID: 8500808437ea
Revises: 8f61a1c27587
Create Date: 2026-02-19 15:43:06.311173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8500808437ea'
down_revision = '8f61a1c27587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processing_claim_token', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_notifications_processing_claim_token'), ['processing_claim_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_notifications_processing_claim_token'))

    op.drop_table('email_notifications')
    # ### end Alembic commands ###
